# Cloudflare Pages Configuration
name = "typescript-portfolio"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "dist"

[site]
bucket = "./dist"

[env.production]
vars = { NODE_VERSION = "18" }

[env.development]
vars = { NODE_VERSION = "18" }
